final List<String> genres = [
  "All",
  "Romance",
  "Adventure",
  "Fantasy",
  "Sci-Fi",
  "Mystery",
  "Thriller",
  "Horror",
  "Comedy",
  "Drama",
  "Slice of Life",
  "Inspirational",
  "Motivational",
  "Personal Growth",
  "Mindfulness",
  "Daily Life",
  "Crime",
  "Action",
  "Supernatural",
  "Historical",
];
